Repository defray-labs/sovryn-lite-ui, pull requests merged in 2021-11, with the labels that each got.

#26 fix(lending): profit calculation for LM lending pools
  src/app/pages/LendPage/components/LendingPool.tsx
  src/utils/blockchain/liquidityMining.ts
Labels: bug

#27 Release v0.0.2
  package.json
  src/app/pages/LendPage/components/LendingPool.tsx
  src/utils/blockchain/liquidityMining.ts
Labels: release

#28 Enable sponsorship for repository
  .github/FUNDING.yml
Labels: internal

#29 internal: update README.md
  README.md
Labels: internal

#31 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: internal

#32 internal: add code of conduct
  CODE_OF_CONDUCT.md
Labels: internal

#33 internal: contributing info
  CONTRIBUTING.md
Labels: internal

#34 internal: add security policy
  SECURITY.md
Labels: internal
